
build:
  # Use the official docker image.
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: build
  when: manual

  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
    - if: $CI_PIPELINE_SOURCE == "web"

  before_script:
    - echo $HARBOR_URL -u "$HARBOR_USERNAME" -p \'$HARBOR_PASSWORD\'
    - docker login $HARBOR_URL -u "$HARBOR_USERNAME" -p "$HARBOR_PASSWORD"
    - apk add openssh-client git
    - echo "deployer" > /etc/hostname

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  script:
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.jomal.pl/jomal/flashcards.git ./src
    - mkdir FLASHCARDS
    - mv compose.yaml ./

    - docker build --pull -t "$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA" .

    - docker tag docker.io/library/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA  $HARBOR_HOST/$HARBOR_PROJECT/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
    - docker tag docker.io/library/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA $HARBOR_HOST/$HARBOR_PROJECT/$CI_COMMIT_REF_NAME:latest
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $HARBOR_HOST/$HARBOR_PROJECT/$CI_COMMIT_REF_NAME:latest
    - mkdir ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-keyscan -p $DEPLOY_PORT $DEPLOY_IP > ~/.ssh/known_hosts
    - echo "$pass"  | base64 -d   > ~/.ssh/key
    - echo '' >> ~/.ssh/key
    - chmod 600 ~/.ssh/key
    - ssh-add ~/.ssh/key > /dev/null
    - export DOCKER_HOST=ssh://$DEPLOY_LOGIN@$DEPLOY_IP:$DEPLOY_PORT

    - cd FLASHCARDS
    - docker compose pull
    - docker compose up -d
    - rm ~/.ssh/key